[icons]
icons = "awesome4"

[[block]]
block = "pomodoro"

[[block]]
block = "net"
format = " $icon ^icon_net_down $speed_down.eng(prefix:K) "
format_alt = " $icon ^icon_net_up $speed_up.eng(prefix:K) "

[[block]]
block = "disk_space"

[[block]]
block = "battery"
format = " $icon $percentage "
full_format = " $icon $percentage "
empty_format = " $icon $percentage "
not_charging_format = " $icon $percentage "

[[block]]
block = "cpu"

[[block]]
block = "temperature"
format = " $icon $average "

[[block]]
block = "nvidia_gpu"

[[block]]
block = "memory"
format = " $icon $mem_used.eng(prefix:Mi) "

[[block]]
block = "backlight"
invert_icons = true

[[block]]
block = "music"
format = " $icon "
[[block.click]]
button = "left"
action = "play_pause"

[[block]]
block = "sound"
max_vol = 100

[[block]]
block = "time"
format = " $icon $timestamp.datetime() "

[[block]]
block = "keyboard_layout"
driver = "kbddbus"

[[block]]
block = "custom"
command = "echo 'RA-L, robotorch'"
