#!/bin/bash

cd $HOME/.dotfiles 
git pull origin master 
git push origin master 

cd $HOME/.config/nvim 
git pull origin master
git push origin master

cd $HOME/Documents/papers_zotero 
git pull origin master
git push origin master

